version: '3.1'
services:
  webserver:
    image: rhythmbhiwani/adhocexam
    restart: always
    environment:
      GOOGLE_OAUTH_CLIENT_ID: XXXXXXXXXXXXXXXXX
      GOOGLE_OAUTH_CLIENT_SECRET: XXXXXXXXXXXXXXXXX
      FACEBOOK_APP_ID: 00000000000000
      FACEBOOK_APP_SECRET: XXXXXXXXXXXXXXXXX
      SESSION_SECRET_KEY: XXXXXXXXXXXXXXXXX
      MONGODB_SERVER_URL: mongodb://XXXXXXXXXXXXXXXXX:27017
      LOGIN_CALLBACK_URL: http://XXXXXXXXXXX:XXXX
      IMGBB_API_KEY: XXXXXXXXXXXXXXXXX
      NODE_ENV: development
    ports:
      - XXXX:3000
