version: "3.1"
services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      GOOGLE_OAUTH_CLIENT_ID: XXXXXXXXXXXXXXXXX
      GOOGLE_OAUTH_CLIENT_SECRET: XXXXXXXXXXXXXXXXX
      FACEBOOK_APP_ID: 00000000000000
      FACEBOOK_APP_SECRET: XXXXXXXXXXXXXXXXX
      SESSION_SECRET_KEY: XXXXXXXXXXXXXXXXX
      MONGODB_SERVER_URL: mongodb://XXXXXXXXXXXXXXXXX:27017
      LOGIN_CALLBACK_URL: http://XXXXXXXXXXX:XXX
      IMGBB_API_KEY: XXXXXXXXXXXXXXXXX
      NODE_ENV: development
      RESEND_KEY: something
    ports:
      - 3000:3000
